import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  const convertUserInput = async (event) => {
    event.preventDefault(); // Prevent page refresh

    // Call the internal API with a POST request

    const response = await fetch(
      '/api/convert',
      {
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          num: event.target.num.value
        }),
        method: 'POST'
      }
    )

    // The result is the response from the API (converted to the JSON format)

    const result = await response.json();

    console.log(result.num); // Log the correct result/response

    event.target.reset();


  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Roman Numeral Converter</h1>

        <h2 className={styles.description}>
          Input a Roman Numeral from 1-1000, and this app will convert it to an integer.
          Enter any integer from 1-1000, and this app will convert it to a Roman Numeral.
        </h2>

        <div className={styles.wrapper}>
          <form onSubmit={convertUserInput} className={styles.form}>
            <label htmlFor="num" className={styles.label}>Enter a number:</label>
            <input type="text" id="num" name="num" required />
          </form> 

          <button className={styles.submit} type="submit">Submit</button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
