import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Roman Numeral Converter</h1>

        <h2 className={styles.description}>
          Input a Roman Numeral from 1-1000, and this app will convert it to an integer.
          Enter any integer from 1-1000, and this app will convert it to a Roman Numeral.
        </h2>

        <div className={styles.wrapper}>
          <form className={styles.form}>
            <label htmlFor="user-input-number" className={styles.label}>Enter a number:</label>
            <input type="text" id="user-input-number" name="user-input-number" />
          </form> 

          <button className={styles.submit} type="submit">Submit</button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
